export default function Home() {
  return (
    <div className="flex flex-1 flex-col items-center justify-center bg-gradient-to-b from-zinc-50 to-white px-6 py-16 text-zinc-900 dark:from-zinc-950 dark:to-zinc-950 dark:text-zinc-50">
      <main className="w-full max-w-3xl">
        <div className="rounded-3xl border border-zinc-200 bg-white p-8 shadow-sm dark:border-zinc-800 dark:bg-zinc-950/60">
          <div className="flex flex-col gap-4">
            <div className="inline-flex items-center gap-2 text-sm font-medium text-zinc-600 dark:text-zinc-300">
              <span className="rounded-full bg-emerald-50 px-3 py-1 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300">
                SDG 3 • Student Well‑Being
              </span>
              <span className="rounded-full bg-zinc-100 px-3 py-1 dark:bg-zinc-900/60">
                Build with AI (Gemini)
              </span>
            </div>
            <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">
              CalmPath: Stress & Burnout First‑Aid
            </h1>
            <p className="text-base leading-7 text-zinc-600 dark:text-zinc-300 sm:text-lg">
              A 2–3 minute check‑in that gives you a clear severity band and a
              personalized next‑7‑days plan generated by Gemini — with safety
              guardrails and a focus on actionable steps, not diagnosis.
            </p>
            <div className="mt-2 grid gap-3 sm:grid-cols-2">
              <a
                href="/checkin"
                className="inline-flex h-12 items-center justify-center rounded-xl bg-zinc-900 px-5 text-sm font-semibold text-white shadow-sm hover:bg-zinc-800 focus:outline-none focus:ring-2 focus:ring-zinc-300 dark:focus:ring-zinc-700"
              >
                Start check‑in
              </a>
              <a
                href="/dashboard"
                className="inline-flex h-12 items-center justify-center rounded-xl border border-zinc-200 bg-white px-5 text-sm font-semibold text-zinc-900 hover:bg-zinc-50 dark:border-zinc-800 dark:bg-zinc-950/30 dark:text-zinc-50 dark:hover:bg-zinc-900/40"
              >
                Impact dashboard
              </a>
            </div>
            <p className="mt-3 text-xs leading-5 text-zinc-500 dark:text-zinc-400">
              Safety note: CalmPath is not medical advice and does not diagnose.
              If you feel unsafe or at risk of self-harm, seek immediate help
              from local emergency services or a trusted person.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
